### ISSUE TITLE
pll_ice40 example missing RESETB

### ISSUE THREAD

**Issue by cbiffle** [adamgreig/amaranth-examples#1]
Hi!

Thanks for these examples, they've been invaluable for exploring the undocumented parts of Amaranth.

Wanted to note that, in my testing here, the `SB_PLL40` blocks need to explicitly have `RESETB` (their active-low reset line) tied to 1 to function. With that change your code (or, really, something derived from your code) seems to work fine. In other words, I added

```
i_RESETB = 1,
```

**Comment by adamgreig** [comment]
Thanks for reporting the issue! This is what I get for copying from a busier production example and cleaning it up without testing the result :sweat_smile:.

I'm sure you're aware anyway, but there's a lot of interesting changes coming to Amaranth for 0.4, especially a more developed system for interfaces and connecting modules together, none of which is covered in these examples yet - the RFCs website covers most of them: https://amaranth-lang.org/rfcs/
